name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo "Instalando dependencias..."
          cd practicacicd
          npm install

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set execute permissions for test file
        run: |
          cd practicacicd
          chmod +x test/index.test.js

      - name: Set execute permissions for node_modules/.bin/jest
        run: |
          cd practicacicd
          chmod +x node_modules/.bin/jest

      - name: Test
        run: |
          echo "Ejecutando pruebas..."
          cd practicacicd
          npm test

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          echo "Construyendo la imagen de Docker..."
          cd practicacicd
          docker build -t practicacicd .

      - name: Deploy to Docker
        run: |
          echo "Desplegando la aplicaci√≥n en Docker..."
          docker run practicacicd